server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: chat-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: your-very-long-secret-key
  expiration: 86400000

jpa:
  hibernate:
  ddl-auto: update
  show-sql: true
